from typing import TypeAlias
from .window import Window
from .label import Label
from .scrolling_label import ScrollingLabel
from .button import Button
from .box import Box
from .calendar import Calendar
from .scale import Scale
from .icon import Icon
from .picture import Picture
from .centerbox import CenterBox
from .revealer import Revealer
from .scroll import Scroll
from .entry import Entry
from .switch import Switch
from .separator import Separator
from .toggle_button import ToggleButton
from .regular_window import RegularWindow
from .file_chooser_button import FileChooserButton
from .file_filter import FileFilter
from .file_dialog import FileDialog
from .grid import Grid
from .menuitem import MenuItem
from .popover_menu import PopoverMenu
from .eventbox import EventBox
from .headerbar import HeaderBar
from .listboxrow import ListBoxRow
from .listbox import ListBox
from .check_button import CheckButton
from .spin_button import SpinButton
from .dropdown import DropDown
from .overlay import Overlay
from .arrow import Arrow
from .arrow_button import ArrowButton
from .revealer_window import RevealerWindow


class Widget:
    Window: TypeAlias = Window
    Label: TypeAlias = Label
    ScrollingLabel: TypeAlias = ScrollingLabel
    Button: TypeAlias = Button
    Box: TypeAlias = Box
    Calendar: TypeAlias = Calendar
    Scale: TypeAlias = Scale
    Icon: TypeAlias = Icon
    CenterBox: TypeAlias = CenterBox
    Revealer: TypeAlias = Revealer
    Scroll: TypeAlias = Scroll
    Entry: TypeAlias = Entry
    Switch: TypeAlias = Switch
    Separator: TypeAlias = Separator
    ToggleButton: TypeAlias = ToggleButton
    RegularWindow: TypeAlias = RegularWindow
    FileChooserButton: TypeAlias = FileChooserButton
    FileFilter: TypeAlias = FileFilter
    Grid: TypeAlias = Grid
    PopoverMenu: TypeAlias = PopoverMenu
    MenuItem: TypeAlias = MenuItem
    EventBox: TypeAlias = EventBox
    FileDialog: TypeAlias = FileDialog
    HeaderBar: TypeAlias = HeaderBar
    ListBoxRow: TypeAlias = ListBoxRow
    ListBox: TypeAlias = ListBox
    Picture: TypeAlias = Picture
    CheckButton: TypeAlias = CheckButton
    SpinButton: TypeAlias = SpinButton
    DropDown: TypeAlias = DropDown
    Overlay: TypeAlias = Overlay
    Arrow: TypeAlias = Arrow
    ArrowButton: TypeAlias = ArrowButton
    RevealerWindow: TypeAlias = RevealerWindow
