name: Release Tarball

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: "Release tag name"
        type: "string"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ github.event.release.tag_name || github.event.inputs.TAG_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.RELEASE_TAG }}

      - name: Install meson
        run: |
          sudo apt update
          sudo apt install -y meson

      - name: Download subprojects
        run: |
          meson subprojects download

      - name: Create tarball
        run: |
          cd ..
          tar -czf ignis.tar.gz ignis

      - name: Upload tarball to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ../ignis.tar.gz
          asset_name: ignis-${{ env.RELEASE_TAG }}.tar.gz
          tag: ${{ env.RELEASE_TAG }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: true
